version: '3.8'
services:
  application:
    container_name: myapplication
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=application
      - DB_USERNAME=root
      - DB_PASSWORD=clovisd12
    ports:
      - 80:8000
    restart: unless-stopped
    volumes:
      - ./src:/var/www/laravel
  mysql:
    container_name: database
    restart: unless-stopped
    ports:
      - 3306:3306
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=clovisd12
      - MYSQL_PASSWORD=clovisd12
      - MYSQL_DATABASE=application
      - MSYQL_USER=root
    volumes:
      - ~/mysql:/var/lib/mysql